# AntiBoom 默认配置
# 可选项：'protect'（阻止破坏方块）、'allow'（允许破坏方块）、'firework'（展示烟花效果并阻止破坏）

explosions:
  creeper: firework
  ghast-fireball: firework
  ender-dragon: protect

explosion-protection:
  enabled: true
  # 是否保护被列入保护清单的挂饰背后的支撑方块（true 表示同时阻止支撑方块被破坏）
  protect-support-blocks: true
  entities:
    painting: true
    armor_stand: true
    item_frame: true
    glow_item_frame: true
    leash_knot: true
  # 可选：按 XYZ 范围定义区域防爆，示例结构如下（去掉注释后生效）：
  xyz-regions:
    - world: world
      min:
        x: 1
        y: 1
        z: 1
      max:
        x: 100
        y: 100
        z: 100
      mode: protect

wind-charge-protection:
  enabled: true
  entities:
    painting: true
    armor_stand: true
    item_frame: true
    glow_item_frame: true
    leash_knot: true
