# AntiBoom 默认配置
# 可选项：'protect'（阻止破坏方块）、'allow'（允许破坏方块）、'firework'（展示烟花效果并阻止破坏）

explosions:
  creeper: firework
  ghast-fireball: firework
  ender-dragon: protect

explosion-protection:
  enabled: true
  # 是否保护被列入保护清单的挂饰背后的支撑方块（true 表示同时阻止支撑方块被破坏）
  protect-support-blocks: true
  entities:
    painting: true
    armor_stand: true
    item_frame: true
    glow_item_frame: true
    # 船类支持别名，例如 oak_boat、oak_chest_boat、bamboo_raft 等
    boat: true
    leash_knot: true

wind-charge-protection:
  enabled: true
  entities:
    painting: true
    armor_stand: true
    item_frame: true
    glow_item_frame: true
    # 船类支持别名，例如 oak_boat、oak_chest_boat、bamboo_raft 等
    boat: true
    leash_knot: true
