name: AntiBoom
version: 1.0.0
main: ict.minesunshineone.antiboom.AntiBoomPlugin
description: "Explosion protection plugin for Paper 1.21 and Folia"
api-version: "1.21"
folia-supported: true
author: MinesunshineOne